spring:
  application:
    name: EffectiveMobileTest
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  data:
    rest:
      detection-strategy: annotated

#logging:
#  level:
#    root: debug

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
